Supraxel/Cusco

- Directory.Build.props
- libs/core/Box.cs
- libs/core/Cusco.Core.csproj
- libs/core/README.md
- libs/csharp-polyfills/README.md
- libs/dispatch/DispatchQueue.cs
- libs/dispatch/Future.cs
- libs/dispatch/IDispatchObject.cs
- libs/dispatch/Promise.cs
- libs/dispatch/README.md
- libs/low-level/Cusco.LowLevel.csproj
- libs/low-level/README.md
- libs/pathfinding/README.md
- libs/unsafe-il/README.md
- 📝 Add a README for each module
> 📝 Add a README for each module

- .circleci/config.yml
- libs/core-test/Cusco.Core.Test.csproj
- libs/core/Cusco.Core.csproj
- libs/core/LICENSE
- libs/csharp-polyfills-test/Cusco.CSharpPolyfills.Test.csproj
- libs/csharp-polyfills/Cusco.CSharpPolyfills.csproj
- libs/csharp-polyfills/LICENSE
- libs/dispatch-test/Cusco.Dispatch.Test.csproj
- libs/dispatch/Cusco.Dispatch.csproj
- libs/dispatch/LICENSE
- libs/low-level-test/Cusco.LowLevel.Test.csproj
- libs/low-level/Cusco.LowLevel.csproj
- libs/low-level/LICENSE
- libs/pathfinding-test/Cusco.Pathfinding.Test.csproj
- libs/pathfinding/Cusco.Pathfinding.csproj
- libs/pathfinding/LICENSE
- libs/unsafe-il/Cusco.UnsafeIL.ilproj
- libs/unsafe-il/LICENSE
> 📝 Add README to NuGet

- README.md
- libs/core/Predicate.cs
- libs/core/README.md
- libs/csharp-polyfills/README.md
- libs/dispatch/README.md
- libs/low-level/README.md
- libs/pathfinding/README.md
- libs/reactivex/Observable_StartWithOperator.cs
- libs/reactivex/PublishSubject.cs
- libs/reactivex/README.md
- libs/unsafe-il/README.md
- ✨ Adding the `PublishSubject<T>` class to the ReactiveX module
- ✨ Adding `Predicate.IsNull` and `Predicate.IsNotNull`
- 📝 Improving both the project and libraries README files
> ✨ ReactiveX: PublishSubject

- libs/reactivex-test/Observable_CompactMapOperatorTests.cs
- libs/reactivex/Observable_CompactMapOperator.cs
- ✨ Add CompactMap Operator
- ✅ Add tests for CompactMap Operator
> ✨ Observable filtering/transforming operator: CompactMap

- libs/reactivex-test/Observable_CompactMapOperatorTests.cs
- libs/reactivex/Observable_CompactMapOperator.cs
- ✨ Add CompactMap Operator for struct/value types
- ✅ Add tests for CompactMap Operator for struct/value types
> ✨ Observable filtering/transforming operator: CompactMap (value types)

- libs/reactivex-test/Cusco.ReactiveX.Test.csproj
- libs/reactivex-test/Observable_MinOperatorTests.cs
- libs/reactivex/Observable_MinOperator.cs
- ✨ Add Min Operator
- ✅ Add tests for Min Operator
> ✨ Observable aggregate operator: Min

- libs/reactivex-test/Observable_MaxOperatorTests.cs
- libs/reactivex/Observable_MaxOperator.cs
- libs/reactivex/Observable_MinOperator.cs
- ✨ Add Max Operator
- ✅ Add tests for Max Operator
> ✨ Observable aggregate operator: Max

- libs/core/IDeepCopyable.cs
> ✨ Add IDeepCopyable

- libs/reactivex-test/Observable_CountTests.cs
- libs/reactivex/Observable_CountOperator.cs
- ✨ Add Count operator for ReactiveX
- ✅ Add tests for Count operator
> ✨ Observable aggregate operator: Count

- libs/core/IDeepCopyable.cs
- ✨ Add IMutableDeepCopyable interface
> ✨ Add IMutableDeepCopyable interface

- libs/reactivex-test/Observable_DistinctUntilChangedOperatorTests.cs
- libs/reactivex/Observable_DistinctUntilChangedOperator.cs
https://rxmarbles.com/#distinctUntilChanged
- ✨Add DistinctUntilChanged
- ✅ Add tests for DistinctUntilChanged
> ✨ Observable utility operator: DistinctUntilChanged

- libs/reactivex-test/Observable_CombineLatestOperatorTests.cs
- libs/reactivex/Observable_CombineLatestOperator.cs
- ✨ Adding CombineLatest operator to ReactiveX
- 🧪 Adding tests for CombineLatest
> ✨ Observable combining operator: CombineLatest

- libs/core/CuscoRT.cs
- ♻️ Detecting Unity at runtime rather than compile-time
- 🐛 Unity doesn't crash anymore when Cusco.Panic is executed
> ♻️ Improving Unity support for CuscoRT

- libs/core-test/ExceptionExtensionsTests.cs
- libs/core/CuscoRT.cs
- libs/core/ExceptionExtensions.cs
- libs/dispatch/MainDispatchQueueImpl.cs
- libs/pathfinding/AStarPathfinder.cs
- libs/pathfinding/IGraphView.cs
- libs/reactivex/BehaviourSubject.cs
- libs/reactivex/PublishSubject.cs
- 🔧 Core: Adding feature flags in CuscoRT. First flag allow disabling of automatic exception enhancing (which is the new default: disabled)
- 🔧 Dispatch: Optimizing main dispatch queue garbage generation
- 🔧 Pathfinding: Breaking change in IGraphView to optimize neighbours evaluation and allow gas limitation
> 🔧 Various small optimizations

- libs/reactivex-test/Observable_CatchOperatorTests.cs
- libs/reactivex/Observable_CatchOperator.cs
- ✨Add Catch Operator
- ✅ Add tests for Catch Operator
> ✨ Observable error handling operator: Catch

- libs/reactivex/IObservableConvertible.cs
- libs/reactivex/Observable+IObservableConvertible.cs
- libs/reactivex/Traits/Infaillible/Infaillible+IObservableConvertible.cs
- libs/reactivex/Traits/Infaillible/Infaillible.cs
- libs/reactivex/Traits/Infaillible/Infaillible_Operators.cs
- ✨ Adding Infaillible trait to ReactiveX
> ✨ Infaillible trait

- libs/low-level/MutexLock.cs
- ✨ Adds MutexLock class for safe Mutex locking
> ✨ Adds MutexLock class for safe Mutex locking

- Cusco.sln
- libs/dependency-injection/Assembler.cs
- libs/dependency-injection/Assembly.cs
- libs/dependency-injection/Container.cs
- libs/dependency-injection/Cusco.DependencyInjection.csproj
- libs/dependency-injection/GraphIdentifier.cs
- libs/dependency-injection/IInstanceStorage.cs
- libs/dependency-injection/IResolver.cs
- libs/dependency-injection/IServiceEntry.cs
- libs/dependency-injection/LICENSE
- libs/dependency-injection/ObjectScope.cs
- libs/dependency-injection/Provider.cs
- libs/dependency-injection/README.md
- libs/dependency-injection/ServiceKey.cs
- libs/dependency-injection/ServiceNotFoundException.cs
- libs/dependency-injection/project.json
- workspace.json
- ✨ Adding `Cusco.DependencyInjection` library
> ✨ Add Cusco.DependencyInjection library

- libs/dispatch/Future.cs
- ✨ Add Transform operator to Futures
> ✨ Add Transform operator

- libs/core/IDeepCopyable.cs
- ♻️ Breaking change in IDeepCopyable to support multiple inheritance
> Change IDeepCopyable to support multiple inheritance
